version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Puerto para la interfaz de gestión web de RabbitMQ
      - "5672:5672"    # Puerto para las conexiones AMQP (usado por tus aplicaciones)
    environment:
      RABBITMQ_DEFAULT_USER: user1
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq_data:
    driver: local
